apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}} 
  labels:
    app: mysql-task
spec:
  ports:
  - port: 3306
    name: mysql
  selector:
    app: mysql-task
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.statefulset.name}} 
spec:
  selector:
    matchLabels:
      app: mysql-task
  serviceName: mysql-lb
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-task
    spec:
      securityContext:
        runAsUser: 65534    #nobody user
        fsGroup: 65534 
      containers:
      - name: mysql
        image: {{.Values.mysqlimage.name}}:{{.Values.mysqlimage.tag}}
        args: ["--ignore-db-dir=lost+found"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-task-pass  
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: task
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: task
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
